table.insert(script, {c = "SETMUSIC", p1 = "intro"})
table.insert(script, {c = "MOVECAMERA", p1 = player.x, p2 = 0})
table.insert(script, {c = "WAIT", p1 = 2})
table.insert(script, {c = "SCROLLLOCK", p1 = "PLAYER", p4 = 32})
table.insert(script, {c = "WAITFORCAMERA"})
table.insert(script, {c = "DIALOG", p1 = -1, p2 = "Welcome to the demo.\nThis is a demo. And you are welcome to it.", p3 = 1})
table.insert(script, {c = "SETMUSIC", p1 = "town_1"})
table.insert(script, {c = "SETFLAG", p1 = 97, p2 = 1})
